import { useState, useEffect } from "react";

import Head from "next/head";
import Image from "next/image";
import HeroImage from "../public/hero.jpg";

import Link from "next/link";
import Page from "../layouts/page";

import { Section } from "../components/Section";

import { Button } from "../components/Button";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

const res200 = {
  text: "1. Continued growth and maturation of the VC sector, with increasing amounts of capital flowing into startups and emerging industries.\n2. A focus on diversity and inclusion, with more VC firms looking to invest in underrepresented founders and ideas.\n3. The rise of environmental, social, and governance (ESG) investing, with more VC firms incorporating sustainability and impact into their investment strategies.\n4. An increasing emphasis on innovation and technology, with artificial intelligence, robotics, and other cutting-edge technologies becoming increasingly important to VC investors.\n5. Continued consolidation and evolution of the VC landscape, with larger, more established firms growing in size and influence, and newer, more specialized firms emerging to focus on specific industries and geographies.",
  info: "success",
};

export default function Home() {
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);

  const token = "rN5HyWPAJ6lj7IqI8BBqdM8zbDYrA6Dq";
  const deets = { data: [0, 0, 0, 0, 0] };

  useEffect(() => {
    setLoading(true);

    // temp
    // setLoading(false);
    // setData(res200);

    fetch("http://20.113.19.4:80/api/v1/service/aks-d80a/score", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(deets),
    })
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
      })
      .catch((err) => console.error(err));
  }, []);

  // if (isLoading) return <p>Loading...</p>;
  // if (!data) return <p>No profile data</p>;

  return (
    <div className="bg-sky-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>

      <Page>
        <div className="flex items-center">
          <div className="lr:pr-8 basis-2/5">
            <h1
              className="
          text-3xl
          font-bold
          mb-2
          0lg:w-3/5
          "
            >
              Your content strategy on autopilot with AI
            </h1>

            <p className="mb-8 text-lg lg:w-3/4">
              Research and create relevant content for your audience 10x faster.
            </p>

            <Button href="#">Get early access</Button>
          </div>
          <div className="lg:pl-8 basis-3/5">
            <Image
              width={592}
              height={592}
              src={"/hero-transparent.png"}
              alt=" "
              priority="true"
            />
          </div>
        </div>
      </Page>
    </div>
  );
}
