import Head from "next/head";
import Image from "next/image";
import HeroImage from "../public/hero.jpg";

import Link from "next/link";
import Page from "../layouts/page";

import { Section } from "../components/Section";

import { Button } from "../components/Button";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

export default function Home() {
  return (
    <div className="bg-sky-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Chivo:wght@400;700;800&display=swap"
          rel="stylesheet"
        ></link>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>

      <Page>
        <div className="flex items-center">
          <div className="lr:pr-8 basis-2/5">
            <h1
              className="
          text-3xl
          font-bold
          mb-2
          0lg:w-3/5
          "
            >
              Your content strategy on autopilot with AI
            </h1>

            <p className="mb-8 text-lg lg:w-3/4">
              Research and create relevant content for your audience 10x faster.
            </p>

            <Button href="#">Get early access</Button>
          </div>
          <div className="lg:pl-8 basis-3/5">
            <Image width={592} height={592} src="/hero-transparent.png"></Image>
          </div>
        </div>
      </Page>
    </div>
  );
}
